### ISSUE TITLE
Circular dependence of util.setup and Paths

### ISSUE THREAD

**Issue by joe-pitt** [mrghg/agage-archive#11]
To generate a config file, you need to run setup from util.py.
util.py calls Paths() on L9, which in turn requires a config file, otherwise it raises a FileNotFoundError (L69)
This circular dependence currently prevents a config file from being written.

**Comment by mrghg** [comment]
There's a quick fix for this in there now (the setup script has this_repo = True, in the call to Paths, which prevents it looking for the config file), but we should probably come up with a better solution at some point, but I think this will work for now.

**Comment by mrghg** [comment]
Decided this workaround is probably fine for now. Closing.
