### ISSUE TITLE
Missing step in workflow?

### ISSUE THREAD

**Issue by joe-pitt** [mrghg/agage-archive#15]
I'm trying to pull the public archive and plot stuff using the tutorial notebook. Am I being stupid, or is there an extra step required after running "dvc pull" in order for this to work? When I pull the archive it gets put at ~/agage-archive/data/agage/agage-public-archive.zip, but as yet there is nothing in my md_path and gcms_path:

  agage:
    md_path: data-nc.zip
    gcms_path: data-gcms-nc.zip
    ale_path: ale_gage_sio1993/ale
    gage_path: ale_gage_sio1993/gage
    output_path: agage-public-archive.zip

This makes tutorial.ipynb fall over when running read_nc with:
"FileNotFoundError: Folder or zip archive /user/home/zh21490/agage-archive/data/agage/data-nc.zip doesn't exist"

**Comment by mrghg** [comment]
Yeah, this isn't very clear... The Tutorial notebook is set up to look at the input data from GCWerks, which should be in your md_path and gcms_path. If you want to look at the processed outputs, use visualise.ipynb.

**Comment by joe-pitt** [comment]
Ah OK makes sense! I have another problem with that - but I will open a separate issue for it...
