### ISSUE TITLE
Plotly renderer - user specific?

### ISSUE THREAD

**Issue by joe-pitt** [mrghg/agage-archive#16]
Having failed for months to get the plot in the visualise notebook working in jupyterlab, I finally found that I needed to change L141 in widgets.py from:
`fig.show(renderer="notebook")`
to
`fig.show(renderer="jupyterlab")`

Presumably it was set to notebook because that works for others? If so then maybe we need to move this into the config file, and tell people to set it appropriately as part of the installation?

**Comment by lukewestern** [comment]
This has been changed to detect on the fly whether jupyter lab or a notebook is being used. Closing issue.
