### ISSUE TITLE
Check for CF compliance and consistency with e.g., GLOBALVIEW obspack

### ISSUE THREAD

**Issue by mrghg** [mrghg/agage-archive#23]
We should make sure the files are as consistent as possible with other data products. Check for CF compliance and also, let's consider using similar variable/file naming as the NOAA GLOBALVIEW+ obspack

**Comment by qq23840** [comment]
obspack variable naming/conventions seem a bit heavy-handed (e.g. 6 different 'time' variables). The only thing I've added is the AGAGE data statements as default attributes.json.

**Comment by qq23840** [comment]
Again this is all un-pushed in the ben_NOAA branch

**Comment by mrghg** [comment]
Implemented in PR #33
