### ISSUE TITLE
TOB not listed in excel files

### ISSUE THREAD

**Issue by Amsoht** [mrghg/agage-archive#61]
TOB is currently not listed in [data_exclude.xlsx](https://github.com/mrghg/agage-archive/blob/a9b2382b3c2a5ec7f0e4cc2be9f535b6834e7714/data/agage/data_exclude.xlsx), [data_combination.xlsx](https://github.com/mrghg/agage-archive/blob/a9b2382b3c2a5ec7f0e4cc2be9f535b6834e7714/data/agage/data_combination.xlsx) and [data_exclude.xlsx](https://github.com/mrghg/agage-archive/blob/a9b2382b3c2a5ec7f0e4cc2be9f535b6834e7714/data/agage/data_exclude.xlsx).
Should I just add it in this (combi_updates_jun24) branch as a commit? Obviously I'd try and copy paste from other stations. Or do you, @mrghg want to do this?

**Comment by mrghg** [comment]
Hi @Amsoht, yes, please just pull the latest version of this branch, add the details to the Excel files, commit and push back

**Comment by Amsoht** [comment]
it seems I can't push to the remote repository:

![grafik](https://github.com/mrghg/agage-archive/assets/57802852/2612442a-b537-42ff-9c29-5596414ae989)

certainly I don't want to create a fork for this. @mrghg could you please grant me write permissions?

**Comment by mrghg** [comment]
Ah, sorry, just gave you access
