### ISSUE TITLE
Wrong start date for files?

### ISSUE THREAD

**Issue by qq23840** [mrghg/agage-archive#75]
THD HCFC-133a record only starts in 2015 or so, but the files produced currently go back to 2004 and have 10 years' worth of NaNs. Is it possible that a `ds.dropna` isn't being called somewhere? Not sure if this affects other files produced. 

Pretty sure there's no record of HCFC-133a being a problem at THD at any stage (nothing in any of the spreadsheets or anything) and no errors are thrown up when using `run.py`

**Comment by mrghg** [comment]
This was the expected behaviour, but we've decided to drop NaNs after discussion internally. The initial idea was that NaNs were retained so that different files aligned. However, this behaviour wouldn't be preserved in the combined files anyway, so removing to make files smaller.
