### ISSUE TITLE
Keep different inlet data separate

### ISSUE THREAD

**Issue by joe-pitt** [mrghg/agage-archive#86]
At the moment if you resample the data (e.g. to hourly) it combines all inlet heights, and outputs the inlet_height variable as the median. We would rather keep the different inlet heights separate, as generally in inversions (intem, elris, rhime) we only use data from the top inlet. One way to do this would be to make inlet_height an index, then resample only on the time index, but there are probably other ways too...

**Comment by mrghg** [comment]
Fixed in PR #96
